Add content-type, Refresh type to list, bump version and date
IIIF/api pull request #1993
Opened 2021-04-28 17:47 UTC by azaroth42

This fixes discovery#86 and discovery#89. As normative changes, they need a new version.

Discovery TSG thinks this is the final version (with possible exception of some editorial clarity) before 1.0

2021-04-28 17:56 UTC, mcwhitaker approved these changes
👍

2021-04-28 17:59 UTC, zimeon requested changes

2021-04-28 17:59 UTC, zimeon commented on source/api/discovery/0.9/index.md
> +If the `Content-Type` header `application/ld+json` cannot be generated, then the `Content-Type` header _SHOULD_ instead be `application/json` (regular JSON), without a `profile` parameter.
In the interest of clarity that we prefer `application/json` over `application/ld+json` without `profile`, should this instead say:

> If the `Content-Type` header `application/ld+json` cannot be generated **with the `profile` parameter**, then the `Content-Type` header _SHOULD_ instead be `application/json` (regular JSON), without a `profile` parameter.

2021-04-28 17:59 UTC, tomcrane submitted a review, later dismissed

2021-04-28 18:01 UTC, kirschbombe approved these changes

2021-04-28 20:40 UTC, mcwhitaker approved these changes

2021-04-28 21:04 UTC, mikeapp approved these changes

2021-04-28 23:40 UTC, kirschbombe approved these changes

2021-04-29 21:37 UTC, zimeon approved these changes

2021-04-29 23:01 UTC, jpstroop approved these changes

2021-05-12 14:02 UTC, merged