add Selectors  section to Registry; move/update imageAPISelector context
IIIF/api pull request #2231
Opened 2023-04-25 20:19 UTC by kirschbombe

This PR:
- creates a new folder/section in the registry for "Selectors"
- edits the old openannotation index page to focus on selectors, not web anno extensions
- copies the current imageAPISelector context from annex to registry/selectors
- updates the imageAPISelector context to point to the current version of image api instead of specific version

I vaguely remember possibly needing a change to the imageAPISelector context for Image 3, but I'm not sure.

2023-04-25 20:28 UTC, mikeapp commented on source/registry/selectors/index.md
> +| region   | "full"    | The string to put in the region parameter of the URI.  |
Would be `max` in v3

2023-04-25 20:29 UTC, mikeapp commented on source/registry/selectors/index.md
> +| size     | "full"    | The string to put in the size parameter of the URI.    |
Would be `max` in v3

2023-04-27 16:11 UTC, zimeon requested changes

2023-04-27 16:23 UTC, zimeon commented on source/registry/selectors/index.md
> +[prezi-rot]: {{ site.api_url | absolute_url }}/presentation/2.0/#rotation "Rotation in Presentation API"
I think \[prezi-rot\] should be in `links.md` and we should also reference prezi 3

2023-04-27 16:31 UTC, azaroth42 commented
Context should use scoped contexts to limit the definition of the properties to only the class.... and define the class.

2023-05-04 18:01 UTC, thehabes commented
Hi all, just sharing some research and results from the JSON LD playground today.

We get `jsonld.SyntaxError: Invalid JSON-LD syntax; invalid scoped context.` from this context as it is now.  We have narrowed it down to two issues

1. This context needs a `"iiif_selectors":"http://iiif.io/api/__TODO__/#"` entry
2. Under `ImageAPISelector` in the `@context` array it tries to scope in "http://iiif.io/api/image/#".  This needs to be the context.json and so should be "https://iiif.io/api/image/3/context.json" if you need that context in there.

I am happy to report that we produced a test object which combined this context, the IIIF Presentation API 3 context, and the Goereference Extension context which was processed correctly in the JSON-LD playground.  It raised a couple other questions that need researched but it is a promising result.  Below is what we found out.

[Go Here ](https://store.rerum.io/v1/id/6453edc3907395217254aefe)to see the test object that we brute force embedded the contexts into.
[See It Process](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=https%3A%2F%2Fstore.rerum.io%2Fv1%2Fid%2F6453edc3907395217254aefe&context=%7B%7D) in the JSON-LD playground.

2023-05-09 06:43 UTC, kirschbombe commented
I added a new `iiif_selectors` context definition to the context file. For the image API context, all other IIIF contexts use the URI pattern `http://iiif.io/api/image/#`, so I left that for now. I did change the https to http.

I also added a note about the ImageApiSelector default values (v3 vs v2).

2023-05-09 20:52 UTC, mikeapp commented on source/registry/selectors/context.json
> +        "http://iiif.io/api/image/#",
I think this should be defined above as `"iiif_image": "http://iiif.io/api/image/#"` and not listed in this `@context`

2023-05-12 16:39 UTC, zimeon requested changes
Minor issue noted with duplicate defn. of `[registry-selectors]` but otherwise looks good

2023-05-31 14:15 UTC, mikeapp submitted a review, later dismissed

2023-09-26 16:52 UTC, kirschbombe commented
The president 3 context is updated to include the selectors context. A big thanks to @thehabes for testing the context and helping me simplify it.

2024-02-28 19:06 UTC, tomcrane approved these changes

2024-02-28 19:28 UTC, azaroth42 approved these changes

2024-03-13 18:08 UTC, mikeapp approved these changes

2024-03-13 18:10 UTC, mixterj approved these changes

2024-03-20 17:33 UTC, JulieWinchester approved these changes

2024-03-20 17:36 UTC, merged